"""Infra constants: ComfyUI endpoint, workflow node IDs, timing, seed pool params."""

COMFY_URL = "http://127.0.0.1:8188"
WORKFLOW_PROMPT_NODE_ID = "6"
WORKFLOW_KSAMPLER_FIRST_NODE_ID = "8"
WORKFLOW_KSAMPLER_SECOND_NODE_ID = "17"
WORKFLOW_IMAGE_SHARPEN_NODE_ID = "23"
WORKFLOW_LATENT_UPSCALE_NODE_ID = "20"
GPU_INDEX = "0"
GPU_IDLE_THRESHOLD = 50
GPU_IDLE_RETRIES = 5
GPU_IDLE_WAIT_SECONDS = 120
COMFY_BOOT_RETRIES = 30
COMFY_BOOT_WAIT_SECONDS = 2
GENERATION_TIMEOUT_SECONDS = 300
HISTORY_POLL_SECONDS = 2
BEST_SEED_MUTATION_RANGE = 5000
BEST_SEED_REUSE_PROBABILITY = 0.7
BEST_SEED_LIMIT = 50
GENERATION_INTERVAL_SECONDS = 14400
AESTHETIC_QUALITY_FLOOR = 4.0
FOCUS_ASSIST_RECHECK_SECONDS = 300
SEED_RATING_LIKE_MULTIPLIER = 1.5
SEED_RATING_DISLIKE_MULTIPLIER = 0.3
